pages = [{"l":"index.html#","e":false,"i":"","n":"New Frontiers","t":"New Frontiers","d":"","k":"static","x":""},
{"l":"org/abh80/nf.html#","e":false,"i":"","n":"org.abh80.nf","t":"org.abh80.nf","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core.html#","e":false,"i":"","n":"org.abh80.nf.core","t":"org.abh80.nf.core","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core/math.html#","e":false,"i":"","n":"org.abh80.nf.core.math","t":"org.abh80.nf.core.math","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core/math/calculus.html#","e":false,"i":"","n":"org.abh80.nf.core.math.calculus","t":"org.abh80.nf.core.math.calculus","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core/math/calculus/Derivative.html#","e":false,"i":"","n":"Derivative","t":"Derivative","d":"org.abh80.nf.core.math.calculus","k":"trait","x":""},
{"l":"org/abh80/nf/core/math/calculus/Derivative.html#getFreeParameters-0","e":false,"i":"","n":"getFreeParameters","t":"getFreeParameters: Int","d":"org.abh80.nf.core.math.calculus.Derivative","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/Derivative.html#getOrder-0","e":false,"i":"","n":"getOrder","t":"getOrder: Int","d":"org.abh80.nf.core.math.calculus.Derivative","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/Derivative.html#getPartialDerivative-e2","e":false,"i":"","n":"getPartialDerivative","t":"getPartialDerivative(orders: Array[Int]): Double","d":"org.abh80.nf.core.math.calculus.Derivative","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/Derivative.html#getValue-0","e":false,"i":"","n":"getValue","t":"getValue: Double","d":"org.abh80.nf.core.math.calculus.Derivative","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/DerivativeWrapper.html#","e":false,"i":"","n":"DerivativeWrapper","t":"DerivativeWrapper(parameters: Int, maxOrder: Int, data: Array[Double]) extends Derivative, Serializable","d":"org.abh80.nf.core.math.calculus","k":"class","x":""},
{"l":"org/abh80/nf/core/math/calculus/DerivativeWrapper.html#getSize-0","e":false,"i":"","n":"getSize","t":"getSize: Int","d":"org.abh80.nf.core.math.calculus.DerivativeWrapper","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#","e":false,"i":"","n":"FiniteDifferencesDifferentiator","t":"FiniteDifferencesDifferentiator(val nbPoints: Int, val stepSize: Double, val tMin: Double, val tMax: Double) extends Serializable","d":"org.abh80.nf.core.math.calculus","k":"class","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#differentiate-be0","e":false,"i":"","n":"differentiate","t":"differentiate(f: Double => Double): Double => Int => Double","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#differentiateToWrapper-fffffb1f","e":false,"i":"","n":"differentiateToWrapper","t":"differentiateToWrapper(f: Double => Double, x: Double, maxOrder: Int): DerivativeWrapper","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"def","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#nbPoints-0","e":false,"i":"","n":"nbPoints","t":"nbPoints: Int","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"val","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#stepSize-0","e":false,"i":"","n":"stepSize","t":"stepSize: Double","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"val","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#tMax-0","e":false,"i":"","n":"tMax","t":"tMax: Double","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"val","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#tMin-0","e":false,"i":"","n":"tMin","t":"tMin: Double","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"val","x":""},
{"l":"org/abh80/nf/core/math/calculus/FiniteDifferencesDifferentiator.html#<init>-fffff71d","e":false,"i":"","n":"this","t":"this(nbPoints: Int, stepSize: Double)","d":"org.abh80.nf.core.math.calculus.FiniteDifferencesDifferentiator","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#","e":false,"i":"","n":"KinematicState","t":"KinematicState(position: Vector3D, velocity: Vector3D, acceleration: Vector3D) extends TimeShiftable[KinematicState]","d":"org.abh80.nf.core.math","k":"class","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#getAngularMomentum-0","e":false,"i":"","n":"getAngularMomentum","t":"getAngularMomentum: Vector3D","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#getAngularVelocity-0","e":false,"i":"","n":"getAngularVelocity","t":"getAngularVelocity: Vector3D","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#negate-0","e":false,"i":"","n":"negate","t":"negate: KinematicState","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#normalize-0","e":false,"i":"","n":"normalize","t":"normalize: KinematicState","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#positionShiftedBy-b4f","e":false,"i":"","n":"positionShiftedBy","t":"positionShiftedBy(dt: Double): Vector3D","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#<init>-fffffe98","e":false,"i":"","n":"this","t":"this(position: Vector3D)","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#<init>-2a0","e":false,"i":"","n":"this","t":"this(position: Vector3D, velocity: Vector3D)","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState.html#velocityShiftedBy-b4f","e":false,"i":"","n":"velocityShiftedBy","t":"velocityShiftedBy(dt: Double): Vector3D","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$.html#","e":false,"i":"","n":"KinematicState","t":"KinematicState","d":"org.abh80.nf.core.math","k":"object","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$.html#BinOp-fffffede","e":false,"i":"","n":"BinOp","t":"BinOp(self: KinematicState): BinOp","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$.html#ZERO-0","e":false,"i":"","n":"ZERO","t":"ZERO: KinematicState","d":"org.abh80.nf.core.math.KinematicState","k":"val","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$.html#velocityBetween-c4f","e":false,"i":"","n":"velocityBetween","t":"velocityBetween(start: Vector3D, end: Vector3D, dt: Double): Vector3D","d":"org.abh80.nf.core.math.KinematicState","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$$BinOp.html#","e":false,"i":"","n":"BinOp","t":"BinOp(self: KinematicState)","d":"org.abh80.nf.core.math.KinematicState","k":"class","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$$BinOp.html#*-fffff3a7","e":false,"i":"","n":"*","t":"*(scalar: Double): KinematicState","d":"org.abh80.nf.core.math.KinematicState.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$$BinOp.html#--400","e":false,"i":"","n":"-","t":"-(second: KinematicState): KinematicState","d":"org.abh80.nf.core.math.KinematicState.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/KinematicState$$BinOp.html#X-400","e":false,"i":"","n":"X","t":"X(second: KinematicState): KinematicState","d":"org.abh80.nf.core.math.KinematicState.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#","e":false,"i":"","n":"Vector3D","t":"Vector3D(x: Double, y: Double, z: Double)","d":"org.abh80.nf.core.math","k":"class","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#angleTo-700","e":false,"i":"","n":"angleTo","t":"angleTo[T <: AngleUnit](second: Vector3D)(factory: Double => T): T","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#distanceTo-c70","e":false,"i":"","n":"distanceTo","t":"distanceTo[T <: DistanceUnit](second: Vector3D)(factory: Double => T): T","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#magnitude-0","e":false,"i":"","n":"magnitude","t":"magnitude: Double","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#negate-0","e":false,"i":"","n":"negate","t":"negate: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#normalize-0","e":false,"i":"","n":"normalize","t":"normalize: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#rotateX-98e","e":false,"i":"","n":"rotateX","t":"rotateX(angle: AngleUnit): Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#rotateY-98e","e":false,"i":"","n":"rotateY","t":"rotateY(angle: AngleUnit): Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D.html#rotateZ-98e","e":false,"i":"","n":"rotateZ","t":"rotateZ(angle: AngleUnit): Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#","e":false,"i":"","n":"Vector3D","t":"Vector3D","d":"org.abh80.nf.core.math","k":"object","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#BinOp-fffff3de","e":false,"i":"","n":"BinOp","t":"BinOp(self: Vector3D): BinOp","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#MINUS_I-0","e":false,"i":"","n":"MINUS_I","t":"MINUS_I: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#MINUS_J-0","e":false,"i":"","n":"MINUS_J","t":"MINUS_J: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#MINUS_K-0","e":false,"i":"","n":"MINUS_K","t":"MINUS_K: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#PLUS_I-0","e":false,"i":"","n":"PLUS_I","t":"PLUS_I: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#PLUS_J-0","e":false,"i":"","n":"PLUS_J","t":"PLUS_J: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#PLUS_K-0","e":false,"i":"","n":"PLUS_K","t":"PLUS_K: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#Zero-0","e":false,"i":"","n":"Zero","t":"Zero: Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"val","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#apply-fffff766","e":false,"i":"","n":"apply","t":"apply(x: DistanceUnit, y: DistanceUnit, z: DistanceUnit): Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$.html#fromArray-fffffbdf","e":false,"i":"","n":"fromArray","t":"fromArray[T <: DistanceUnit](arr: Array[T]): Vector3D","d":"org.abh80.nf.core.math.Vector3D","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#","e":false,"i":"","n":"BinOp","t":"BinOp(self: Vector3D)","d":"org.abh80.nf.core.math.Vector3D","k":"class","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#*-b4f","e":false,"i":"","n":"*","t":"*(scalar: Double): Vector3D","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#+-ffffff00","e":false,"i":"","n":"+","t":"+(other: Vector3D): Vector3D","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#--ffffff00","e":false,"i":"","n":"-","t":"-(other: Vector3D): Vector3D","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#/-b4f","e":false,"i":"","n":"/","t":"/(scalar: Double): Vector3D","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#X-ffffff00","e":false,"i":"","n":"X","t":"X(other: Vector3D): Vector3D","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#dot-fffff5a1","e":false,"i":"","n":"dot","t":"dot(other: Vector3D): Double","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/math/Vector3D$$BinOp.html#~-f5f","e":false,"i":"","n":"~","t":"~(other: Vector3D, epsilon: Double): Boolean","d":"org.abh80.nf.core.math.Vector3D.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics.html#","e":false,"i":"","n":"org.abh80.nf.core.metrics","t":"org.abh80.nf.core.metrics","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit.html#","e":false,"i":"","n":"AngleUnit","t":"AngleUnit","d":"org.abh80.nf.core.metrics","k":"trait","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit.html#fromRadians-ffffff01","e":false,"i":"","n":"fromRadians","t":"fromRadians(rad: Double): AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit.html#symbol-0","e":false,"i":"","n":"symbol","t":"symbol: String","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit.html#toRadians-0","e":false,"i":"","n":"toRadians","t":"toRadians: Double","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit.html#value-0","e":false,"i":"","n":"value","t":"value: Double","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$.html#","e":false,"i":"","n":"AngleUnit","t":"AngleUnit","d":"org.abh80.nf.core.metrics","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$.html#BinOp-51e","e":false,"i":"","n":"BinOp","t":"BinOp(self: AngleUnit): BinOp","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$.html#fromRadians-2d3","e":false,"i":"","n":"fromRadians","t":"fromRadians[T <: AngleUnit](rad: Double, unitFactory: Double => T): T","d":"org.abh80.nf.core.metrics.AngleUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$ArcMinute.html#","e":false,"i":"","n":"ArcMinute","t":"ArcMinute(value: Double) extends AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$ArcMinute$.html#","e":false,"i":"","n":"ArcMinute","t":"ArcMinute extends AngleUnitCompanion[ArcMinute]","d":"org.abh80.nf.core.metrics.AngleUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$ArcSecond.html#","e":false,"i":"","n":"ArcSecond","t":"ArcSecond(value: Double) extends AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$ArcSecond$.html#","e":false,"i":"","n":"ArcSecond","t":"ArcSecond extends AngleUnitCompanion[ArcSecond]","d":"org.abh80.nf.core.metrics.AngleUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#","e":false,"i":"","n":"BinOp","t":"BinOp(self: AngleUnit)","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#*-fffff5c0","e":false,"i":"","n":"*","t":"*(second: AngleUnit): AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#+-fffff5c0","e":false,"i":"","n":"+","t":"+(second: AngleUnit): AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#--fffff5c0","e":false,"i":"","n":"-","t":"-(second: AngleUnit): AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#/-fffff5c0","e":false,"i":"","n":"/","t":"/(second: AngleUnit): AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$BinOp.html#~-fffffc6d","e":false,"i":"","n":"~","t":"~(second: AngleUnit, epsilon: Double): Boolean","d":"org.abh80.nf.core.metrics.AngleUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$Degree.html#","e":false,"i":"","n":"Degree","t":"Degree(value: Double) extends AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$Degree$.html#","e":false,"i":"","n":"Degree","t":"Degree extends AngleUnitCompanion[Degree]","d":"org.abh80.nf.core.metrics.AngleUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$HourAngle.html#","e":false,"i":"","n":"HourAngle","t":"HourAngle(value: Double) extends AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$HourAngle$.html#","e":false,"i":"","n":"HourAngle","t":"HourAngle extends AngleUnitCompanion[HourAngle]","d":"org.abh80.nf.core.metrics.AngleUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnit$$Radian.html#","e":false,"i":"","n":"Radian","t":"Radian(value: Double) extends AngleUnit","d":"org.abh80.nf.core.metrics.AngleUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnitCompanion.html#","e":false,"i":"","n":"AngleUnitCompanion","t":"AngleUnitCompanion[T <: AngleUnit]","d":"org.abh80.nf.core.metrics","k":"trait","x":""},
{"l":"org/abh80/nf/core/metrics/AngleUnitCompanion.html#fromRadians-ffffff01","e":false,"i":"","n":"fromRadians","t":"fromRadians(radians: Double): T","d":"org.abh80.nf.core.metrics.AngleUnitCompanion","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit.html#","e":false,"i":"","n":"DistanceUnit","t":"DistanceUnit","d":"org.abh80.nf.core.metrics","k":"trait","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit.html#fromMeter-fffff8cf","e":false,"i":"","n":"fromMeter","t":"fromMeter(meters: Double): DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit.html#symbol-0","e":false,"i":"","n":"symbol","t":"symbol: String","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit.html#toMeter-0","e":false,"i":"","n":"toMeter","t":"toMeter: Double","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit.html#value-0","e":false,"i":"","n":"value","t":"value: Double","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$.html#","e":false,"i":"","n":"DistanceUnit","t":"DistanceUnit","d":"org.abh80.nf.core.metrics","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$.html#BinOp-5f2","e":false,"i":"","n":"BinOp","t":"BinOp(self: DistanceUnit): BinOp","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$.html#fromMeters-fffffbbd","e":false,"i":"","n":"fromMeters","t":"fromMeters[T <: DistanceUnit](meters: Double, unitFactory: Double => T): T","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$AstronomicalUnit.html#","e":false,"i":"","n":"AstronomicalUnit","t":"AstronomicalUnit(value: Double) extends DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$AstronomicalUnit$.html#","e":false,"i":"","n":"AstronomicalUnit","t":"AstronomicalUnit extends DistanceUnitCompanion[AstronomicalUnit]","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$AstronomicalUnit$.html#apply-6cf","e":false,"i":"","n":"apply","t":"apply(value: Double): AstronomicalUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.AstronomicalUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$AstronomicalUnit$.html#fromMeter-6cf","e":false,"i":"","n":"fromMeter","t":"fromMeter(meters: Double): AstronomicalUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.AstronomicalUnit","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#","e":false,"i":"","n":"BinOp","t":"BinOp(self: DistanceUnit)","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#*-b6c","e":false,"i":"","n":"*","t":"*(second: DistanceUnit): DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#+-b6c","e":false,"i":"","n":"+","t":"+(second: DistanceUnit): DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#--b6c","e":false,"i":"","n":"-","t":"-(second: DistanceUnit): DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#/-b6c","e":false,"i":"","n":"/","t":"/(second: DistanceUnit): DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$BinOp.html#~-fffff531","e":false,"i":"","n":"~","t":"~(second: DistanceUnit, epsilon: Double): Boolean","d":"org.abh80.nf.core.metrics.DistanceUnit.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$Kilometer.html#","e":false,"i":"","n":"Kilometer","t":"Kilometer(value: Double) extends DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$Kilometer$.html#","e":false,"i":"","n":"Kilometer","t":"Kilometer extends DistanceUnitCompanion[Kilometer]","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"object","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$Kilometer$.html#apply-b2f","e":false,"i":"","n":"apply","t":"apply(value: Double): Kilometer","d":"org.abh80.nf.core.metrics.DistanceUnit.Kilometer","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$Kilometer$.html#fromMeter-b2f","e":false,"i":"","n":"fromMeter","t":"fromMeter(meters: Double): Kilometer","d":"org.abh80.nf.core.metrics.DistanceUnit.Kilometer","k":"def","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnit$$Meter.html#","e":false,"i":"","n":"Meter","t":"Meter(value: Double) extends DistanceUnit","d":"org.abh80.nf.core.metrics.DistanceUnit","k":"class","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnitCompanion.html#","e":false,"i":"","n":"DistanceUnitCompanion","t":"DistanceUnitCompanion[T <: DistanceUnit]","d":"org.abh80.nf.core.metrics","k":"trait","x":""},
{"l":"org/abh80/nf/core/metrics/DistanceUnitCompanion.html#fromMeter-fffff8cf","e":false,"i":"","n":"fromMeter","t":"fromMeter(meters: Double): T","d":"org.abh80.nf.core.metrics.DistanceUnitCompanion","k":"def","x":""},
{"l":"org/abh80/nf/core/time.html#","e":false,"i":"","n":"org.abh80.nf.core.time","t":"org.abh80.nf.core.time","d":"","k":"package","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#","e":false,"i":"","n":"AbsoluteTime","t":"AbsoluteTime(tf: TimeFormat) extends TimeFormat, Comparable[TimeFormat], Serializable, TimeShiftable[AbsoluteTime]","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#++-b8f","e":false,"i":"","n":"++","t":"++(shiftBy: Long): AbsoluteTime","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#++-1a","e":false,"i":"","n":"++","t":"++(shiftBy: Double): AbsoluteTime","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#durationFrom-e60","e":false,"i":"","n":"durationFrom","t":"durationFrom(time: AbsoluteTime): TimeFormat","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#getDateTime-fa0","e":false,"i":"","n":"getDateTime","t":"getDateTime(scale: TimeScale): (Date, Time)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#offsetBetween-fffff8f7","e":false,"i":"","n":"offsetBetween","t":"offsetBetween(scale1: TimeScale, scale2: TimeScale): TimeFormat","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-853","e":false,"i":"","n":"this","t":"this()","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-fffff6c6","e":false,"i":"","n":"this","t":"this(date: Date, time: Time, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-6d9","e":false,"i":"","n":"this","t":"this(year: Int, month: Int, day: Int, hour: Int, minute: Int, seconds: TimeFormat, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-da5","e":false,"i":"","n":"this","t":"this(year: Int, month: Int, day: Int, hour: Int, minute: Int, seconds: Double, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-fffffa29","e":false,"i":"","n":"this","t":"this(year: Int, month: Month, day: Int, hour: Int, minute: Int, seconds: TimeFormat, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-fffff855","e":false,"i":"","n":"this","t":"this(year: Int, month: Month, day: Int, hour: Int, minute: Int, seconds: Double, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-ce8","e":false,"i":"","n":"this","t":"this(date: Date, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-b7e","e":false,"i":"","n":"this","t":"this(year: Int, month: Int, day: Int, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-8b9","e":false,"i":"","n":"this","t":"this(instant: Instant, scale: TimeScale)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#<init>-fffff4e7","e":false,"i":"","n":"this","t":"this(instant: Instant)","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime.html#toString-ffffffd3","e":false,"i":"","n":"toString","t":"toString(scale: TimeScale): String","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime$.html#","e":false,"i":"","n":"AbsoluteTime","t":"AbsoluteTime","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime$.html#fromMJDDate-d35","e":false,"i":"","n":"fromMJDDate","t":"fromMJDDate(mjd: Int, timeScale: TimeScale, seconds: TimeFormat): AbsoluteTime","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/AbsoluteTime$.html#now-853","e":false,"i":"","n":"now","t":"now(): AbsoluteTime","d":"org.abh80.nf.core.time.AbsoluteTime","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#","e":false,"i":"","n":"Date","t":"Date extends Comparable[Date], Serializable","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getDay-0","e":false,"i":"","n":"getDay","t":"getDay: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getDayOfWeek-0","e":false,"i":"","n":"getDayOfWeek","t":"getDayOfWeek: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getDayOfYear-0","e":false,"i":"","n":"getDayOfYear","t":"getDayOfYear: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getJ2000Day-0","e":false,"i":"","n":"getJ2000Day","t":"getJ2000Day: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getJulianDay-0","e":false,"i":"","n":"getJulianDay","t":"getJulianDay: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getMJD-0","e":false,"i":"","n":"getMJD","t":"getMJD: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getMonth-0","e":false,"i":"","n":"getMonth","t":"getMonth: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getMonthAsEnum-0","e":false,"i":"","n":"getMonthAsEnum","t":"getMonthAsEnum: Month","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getWeek-0","e":false,"i":"","n":"getWeek","t":"getWeek: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#getYear-0","e":false,"i":"","n":"getYear","t":"getYear: Int","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#<init>-276","e":false,"i":"","n":"this","t":"this(year: Int, month: Int, day: Int)","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#<init>-fffff696","e":false,"i":"","n":"this","t":"this(j2000DayOffset: Int)","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#<init>-fffff6b1","e":false,"i":"","n":"this","t":"this(instant: Instant)","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date.html#toString-fffff4f8","e":false,"i":"","n":"toString","t":"toString(f: (Int, Int, Int) => StringDateFormat): String","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#","e":false,"i":"","n":"Date","t":"Date","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#CXCSEC-0","e":false,"i":"","n":"CXCSEC","t":"CXCSEC: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#GLONASS-0","e":false,"i":"","n":"GLONASS","t":"GLONASS: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#GPS-0","e":false,"i":"","n":"GPS","t":"GPS: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#J2000_0-0","e":false,"i":"","n":"J2000_0","t":"J2000_0: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#JULIAN-0","e":false,"i":"","n":"JULIAN","t":"JULIAN: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#MJD-0","e":false,"i":"","n":"MJD","t":"MJD: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#NAVIC-0","e":false,"i":"","n":"NAVIC","t":"NAVIC: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#UNIX-0","e":false,"i":"","n":"UNIX","t":"UNIX: Date","d":"org.abh80.nf.core.time.Date","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#apply-fffff696","e":false,"i":"","n":"apply","t":"apply(j2000Offset: Int): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#apply-126","e":false,"i":"","n":"apply","t":"apply(year: Int, month: Month, day: Int): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#apply-e3d","e":false,"i":"","n":"apply","t":"apply(year: Int, days: Int): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#apply-276","e":false,"i":"","n":"apply","t":"apply(year: Int, month: Int, day: Int): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#apply-233","e":false,"i":"","n":"apply","t":"apply(epoch: Date, j2000Offset: Int): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Date$.html#now-fffff61d","e":false,"i":"","n":"now","t":"now(): Date","d":"org.abh80.nf.core.time.Date","k":"def","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#","e":false,"i":"","n":"EpochFactory","t":"EpochFactory","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#CXCSEC-0","e":false,"i":"","n":"CXCSEC","t":"CXCSEC: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#GLONASS-0","e":false,"i":"","n":"GLONASS","t":"GLONASS: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#GPS-0","e":false,"i":"","n":"GPS","t":"GPS: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#J1900-0","e":false,"i":"","n":"J1900","t":"J1900: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#J2000_0-0","e":false,"i":"","n":"J2000_0","t":"J2000_0: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#JULIAN-0","e":false,"i":"","n":"JULIAN","t":"JULIAN: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#NAVIC-0","e":false,"i":"","n":"NAVIC","t":"NAVIC: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/EpochFactory$.html#UNIX-0","e":false,"i":"","n":"UNIX","t":"UNIX: AbsoluteTime","d":"org.abh80.nf.core.time.EpochFactory","k":"val","x":""},
{"l":"org/abh80/nf/core/time/FixedTimeOffsetScale.html#","e":false,"i":"","n":"FixedTimeOffsetScale","t":"FixedTimeOffsetScale(val name: String, val offset: TimeFormat) extends TimeScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/FixedTimeOffsetScale.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"org.abh80.nf.core.time.FixedTimeOffsetScale","k":"val","x":""},
{"l":"org/abh80/nf/core/time/FixedTimeOffsetScale.html#offset-0","e":false,"i":"","n":"offset","t":"offset: TimeFormat","d":"org.abh80.nf.core.time.FixedTimeOffsetScale","k":"val","x":""},
{"l":"org/abh80/nf/core/time/GLONASSScale.html#","e":false,"i":"","n":"GLONASSScale","t":"GLONASSScale(utc: TimeScale) extends TimeScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/GLONASSScale.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"org.abh80.nf.core.time.GLONASSScale","k":"val","x":""},
{"l":"org/abh80/nf/core/time/GPSScale.html#","e":false,"i":"","n":"GPSScale","t":"GPSScale extends FixedTimeOffsetScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/IRNSSScale.html#","e":false,"i":"","n":"IRNSSScale","t":"IRNSSScale extends FixedTimeOffsetScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TAIScale.html#","e":false,"i":"","n":"TAIScale","t":"TAIScale extends FixedTimeOffsetScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TDBScale.html#","e":false,"i":"","n":"TDBScale","t":"TDBScale(val tt: TimeScale, j2000Epoch: AbsoluteTime) extends TimeScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TDBScale.html#tt-0","e":false,"i":"","n":"tt","t":"tt: TimeScale","d":"org.abh80.nf.core.time.TDBScale","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TDTScale.html#","e":false,"i":"","n":"TDTScale","t":"TDTScale extends TTScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TTScale.html#","e":false,"i":"","n":"TTScale","t":"TTScale extends FixedTimeOffsetScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/Time.html#","e":false,"i":"","n":"Time","t":"Time extends Comparable[Time], Serializable","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getHour-0","e":false,"i":"","n":"getHour","t":"getHour: Int","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getMinute-0","e":false,"i":"","n":"getMinute","t":"getMinute: Int","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getSeconds-0","e":false,"i":"","n":"getSeconds","t":"getSeconds: Double","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getSecondsAsTimeFormat-0","e":false,"i":"","n":"getSecondsAsTimeFormat","t":"getSecondsAsTimeFormat: TimeFormat","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getSecondsInDay-0","e":false,"i":"","n":"getSecondsInDay","t":"getSecondsInDay: Double","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getSecondsInDayObject-fffff20c","e":false,"i":"","n":"getSecondsInDayObject","t":"getSecondsInDayObject(offset: Int): TimeFormat","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getSecondsInUTCDay-0","e":false,"i":"","n":"getSecondsInUTCDay","t":"getSecondsInUTCDay: Double","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getUTCOffsetString-0","e":false,"i":"","n":"getUTCOffsetString","t":"getUTCOffsetString: String","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#getUtcOffset-0","e":false,"i":"","n":"getUtcOffset","t":"getUtcOffset: Int","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffffca8","e":false,"i":"","n":"this","t":"this(hour: Int, minute: Int, seconds: TimeFormat, utcOffset: Int)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffff6ae","e":false,"i":"","n":"this","t":"this(hour: Int, minute: Int, seconds: Double, utcOffset: Int)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-8e9","e":false,"i":"","n":"this","t":"this(hour: Int, minute: Int, seconds: TimeFormat)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffff023","e":false,"i":"","n":"this","t":"this(hour: Int, minute: Int, seconds: Double)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffff9d0","e":false,"i":"","n":"this","t":"this(instant: Instant)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffffd09","e":false,"i":"","n":"this","t":"this(seconds: TimeFormat)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-803","e":false,"i":"","n":"this","t":"this(seconds: Double)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#<init>-fffff015","e":false,"i":"","n":"this","t":"this(seconds: TimeFormat, leap: TimeFormat, minuteDuration: Int)","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#toISO8601String-78c","e":false,"i":"","n":"toISO8601String","t":"toISO8601String(secondsPrecision: Int): String","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time.html#toISO8601StringTrimmed-78c","e":false,"i":"","n":"toISO8601StringTrimmed","t":"toISO8601StringTrimmed(secondsPrecision: Int): String","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/Time$.html#","e":false,"i":"","n":"Time","t":"Time","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/Time$.html#AFTERNOON-0","e":false,"i":"","n":"AFTERNOON","t":"AFTERNOON: Time","d":"org.abh80.nf.core.time.Time","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Time$.html#MIDNIGHT-0","e":false,"i":"","n":"MIDNIGHT","t":"MIDNIGHT: Time","d":"org.abh80.nf.core.time.Time","k":"val","x":""},
{"l":"org/abh80/nf/core/time/Time$.html#now-0","e":false,"i":"","n":"now","t":"now: Time","d":"org.abh80.nf.core.time.Time","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#","e":false,"i":"","n":"TimeFormat","t":"TimeFormat(var seconds: Long, var attoseconds: Long) extends Comparable[TimeFormat], Serializable","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#getAttoSeconds-0","e":false,"i":"","n":"getAttoSeconds","t":"getAttoSeconds: Long","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#getRoundedFormat-fffff20c","e":false,"i":"","n":"getRoundedFormat","t":"getRoundedFormat(precision: Int): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#getSeconds-0","e":false,"i":"","n":"getSeconds","t":"getSeconds: Long","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#isZero-0","e":false,"i":"","n":"isZero","t":"isZero: Boolean","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#negate-fffff053","e":false,"i":"","n":"negate","t":"negate(): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#<init>-fffff660","e":false,"i":"","n":"this","t":"this(tf: TimeFormat)","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat.html#toDouble-0","e":false,"i":"","n":"toDouble","t":"toDouble: Double","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#","e":false,"i":"","n":"TimeFormat","t":"TimeFormat","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#ATTOSECOND-0","e":false,"i":"","n":"ATTOSECOND","t":"ATTOSECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#BinOp-7e","e":false,"i":"","n":"BinOp","t":"BinOp(self: TimeFormat): BinOp","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#DAY-0","e":false,"i":"","n":"DAY","t":"DAY: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#FEMTOSECOND-0","e":false,"i":"","n":"FEMTOSECOND","t":"FEMTOSECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#HOUR-0","e":false,"i":"","n":"HOUR","t":"HOUR: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#MICROSECOND-0","e":false,"i":"","n":"MICROSECOND","t":"MICROSECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#MILLISECOND-0","e":false,"i":"","n":"MILLISECOND","t":"MILLISECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#MINUTE-0","e":false,"i":"","n":"MINUTE","t":"MINUTE: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#NANOSECOND-0","e":false,"i":"","n":"NANOSECOND","t":"NANOSECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#PICOSECOND-0","e":false,"i":"","n":"PICOSECOND","t":"PICOSECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#SECOND-0","e":false,"i":"","n":"SECOND","t":"SECOND: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#Zero-0","e":false,"i":"","n":"Zero","t":"Zero: TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#fromDouble-dda","e":false,"i":"","n":"fromDouble","t":"fromDouble(seconds: Double): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$.html#fromTimeUnit-fffff9b7","e":false,"i":"","n":"fromTimeUnit","t":"fromTimeUnit(value: Long, unit: TimeUnit): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$$BinOp.html#","e":false,"i":"","n":"BinOp","t":"BinOp(self: TimeFormat)","d":"org.abh80.nf.core.time.TimeFormat","k":"class","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$$BinOp.html#*-fffff28f","e":false,"i":"","n":"*","t":"*(scalar: Long): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$$BinOp.html#+-fffff660","e":false,"i":"","n":"+","t":"+(second: TimeFormat): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$$BinOp.html#--fffff660","e":false,"i":"","n":"-","t":"-(second: TimeFormat): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeFormat$$BinOp.html#/-fffff28f","e":false,"i":"","n":"/","t":"/(scalar: Long): TimeFormat","d":"org.abh80.nf.core.time.TimeFormat.BinOp","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#","e":false,"i":"","n":"TimeScale","t":"TimeScale","d":"org.abh80.nf.core.time","k":"trait","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#getLastLeapSecond-0","e":false,"i":"","n":"getLastLeapSecond","t":"getLastLeapSecond: TimeFormat","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#getLeap-e60","e":false,"i":"","n":"getLeap","t":"getLeap(time: AbsoluteTime): TimeFormat","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#getName-0","e":false,"i":"","n":"getName","t":"getName: String","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#isInsideLeapSecond-fffffded","e":false,"i":"","n":"isInsideLeapSecond","t":"isInsideLeapSecond(time: AbsoluteTime): Boolean","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#minuteDuration-fffff434","e":false,"i":"","n":"minuteDuration","t":"minuteDuration(time: AbsoluteTime): Int","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"org.abh80.nf.core.time.TimeScale","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#timePastTAI-e60","e":false,"i":"","n":"timePastTAI","t":"timePastTAI(time: AbsoluteTime): TimeFormat","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScale.html#timeToTAI-334","e":false,"i":"","n":"timeToTAI","t":"timeToTAI(date: Date, time: Time): TimeFormat","d":"org.abh80.nf.core.time.TimeScale","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#","e":false,"i":"","n":"TimeScaleFactory","t":"TimeScaleFactory","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getGLONASS-0","e":false,"i":"","n":"getGLONASS","t":"getGLONASS: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getGPS-0","e":false,"i":"","n":"getGPS","t":"getGPS: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getIRNSS-0","e":false,"i":"","n":"getIRNSS","t":"getIRNSS: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getTAI-0","e":false,"i":"","n":"getTAI","t":"getTAI: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getTDB-0","e":false,"i":"","n":"getTDB","t":"getTDB: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getTDT-0","e":false,"i":"","n":"getTDT","t":"getTDT: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getTT-0","e":false,"i":"","n":"getTT","t":"getTT: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeScaleFactory$.html#getUTC-0","e":false,"i":"","n":"getUTC","t":"getUTC: TimeScale","d":"org.abh80.nf.core.time.TimeScaleFactory","k":"def","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#","e":false,"i":"","n":"TimeUnit","t":"TimeUnit","d":"org.abh80.nf.core.time","k":"enum","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#DAYS-0","e":false,"i":"","n":"DAYS","t":"DAYS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#HOURS-0","e":false,"i":"","n":"HOURS","t":"HOURS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#MINUTES-0","e":false,"i":"","n":"MINUTES","t":"MINUTES extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#SECONDS-0","e":false,"i":"","n":"SECONDS","t":"SECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#MILLISECONDS-0","e":false,"i":"","n":"MILLISECONDS","t":"MILLISECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#MICROSECONDS-0","e":false,"i":"","n":"MICROSECONDS","t":"MICROSECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#NANOSECONDS-0","e":false,"i":"","n":"NANOSECONDS","t":"NANOSECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#PICOSECONDS-0","e":false,"i":"","n":"PICOSECONDS","t":"PICOSECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#FEMTOSECONDS-0","e":false,"i":"","n":"FEMTOSECONDS","t":"FEMTOSECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/TimeUnit.html#ATTOSECONDS-0","e":false,"i":"","n":"ATTOSECONDS","t":"ATTOSECONDS extends TimeUnit","d":"org.abh80.nf.core.time.TimeUnit","k":"val","x":""},
{"l":"org/abh80/nf/core/time/UTCScale.html#","e":false,"i":"","n":"UTCScale","t":"UTCScale(tai: TimeScale, leapOffsets: Array[LeapSecondOffset]) extends TimeScale","d":"org.abh80.nf.core.time","k":"class","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$.html#","e":false,"i":"","n":"UTCScale","t":"UTCScale","d":"org.abh80.nf.core.time","k":"object","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$ComputedLeapSecondOffset.html#","e":false,"i":"","n":"ComputedLeapSecondOffset","t":"ComputedLeapSecondOffset(startTime: AbsoluteTime, mjdDate: Int, mjdBaseTime: AbsoluteTime, mjdBase: Int, fixedOffset: TimeFormat, rate: Int, leap: TimeFormat)","d":"org.abh80.nf.core.time.UTCScale","k":"class","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$ComputedLeapSecondOffset.html#offsetFrom-e60","e":false,"i":"","n":"offsetFrom","t":"offsetFrom(time: AbsoluteTime): TimeFormat","d":"org.abh80.nf.core.time.UTCScale.ComputedLeapSecondOffset","k":"def","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$ComputedLeapSecondOffset.html#offsetFrom-334","e":false,"i":"","n":"offsetFrom","t":"offsetFrom(date: Date, time: Time): TimeFormat","d":"org.abh80.nf.core.time.UTCScale.ComputedLeapSecondOffset","k":"def","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$ComputedLeapSecondOffset.html#validityStart-0","e":false,"i":"","n":"validityStart","t":"validityStart: AbsoluteTime","d":"org.abh80.nf.core.time.UTCScale.ComputedLeapSecondOffset","k":"val","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$LeapSecondOffset.html#","e":false,"i":"","n":"LeapSecondOffset","t":"LeapSecondOffset(startDate: Date, mjdBase: Int, fixedOffset: Double, rate: Double)(implicit tai: TimeScale)","d":"org.abh80.nf.core.time.UTCScale","k":"class","x":""},
{"l":"org/abh80/nf/core/time/UTCScale$$LeapSecondOffset.html#getComputedOffset-460","e":false,"i":"","n":"getComputedOffset","t":"getComputedOffset(previousOffset: ComputedLeapSecondOffset): ComputedLeapSecondOffset","d":"org.abh80.nf.core.time.UTCScale.LeapSecondOffset","k":"def","x":""},
{"l":"org/abh80/nf/core/Constants$.html#","e":false,"i":"","n":"Constants","t":"Constants","d":"org.abh80.nf.core","k":"object","x":""},
{"l":"org/abh80/nf/core/Constants$.html#SECONDS_IN_A_JULIAN_DAY-0","e":false,"i":"","n":"SECONDS_IN_A_JULIAN_DAY","t":"SECONDS_IN_A_JULIAN_DAY: Long","d":"org.abh80.nf.core.Constants","k":"val","x":""},
{"l":"org/abh80/nf/frames.html#","e":false,"i":"","n":"org.abh80.nf.frames","t":"org.abh80.nf.frames","d":"","k":"package","x":""},
{"l":"org/abh80/nf/frames/transformer.html#","e":false,"i":"","n":"org.abh80.nf.frames.transformer","t":"org.abh80.nf.frames.transformer","d":"","k":"package","x":""},
{"l":"org/abh80/nf/frames/transformer/ReferenceFrameTransform.html#","e":false,"i":"","n":"ReferenceFrameTransform","t":"ReferenceFrameTransform(fromRef: Frame, toFrame: Frame, priority: Double)","d":"org.abh80.nf.frames.transformer","k":"trait","x":""},
{"l":"org/abh80/nf/frames/transformer/ReferenceFrameTransformProvider.html#","e":false,"i":"","n":"ReferenceFrameTransformProvider","t":"ReferenceFrameTransformProvider","d":"org.abh80.nf.frames.transformer","k":"trait","x":""},
{"l":"org/abh80/nf/frames/transformer/ReferenceFrameTransformProvider.html#getTransform-d97","e":false,"i":"","n":"getTransform","t":"getTransform(time: AbsoluteTime): ReferenceFrameTransform","d":"org.abh80.nf.frames.transformer.ReferenceFrameTransformProvider","k":"def","x":""},
{"l":"org/abh80/nf/frames/transformer/StaticReferenceFrameTransform.html#","e":false,"i":"","n":"StaticReferenceFrameTransform","t":"StaticReferenceFrameTransform","d":"org.abh80.nf.frames.transformer","k":"trait","x":""},
{"l":"org/abh80/nf/frames/DefaultFrames.html#","e":false,"i":"","n":"DefaultFrames","t":"DefaultFrames(name: String)","d":"org.abh80.nf.frames","k":"enum","x":""},
{"l":"org/abh80/nf/frames/DefaultFrames.html#GCRF-0","e":false,"i":"","n":"GCRF","t":"GCRF extends DefaultFrames","d":"org.abh80.nf.frames.DefaultFrames","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame.html#","e":false,"i":"","n":"Frame","t":"Frame","d":"org.abh80.nf.frames","k":"class","x":""},
{"l":"org/abh80/nf/frames/Frame.html#depth-0","e":false,"i":"","n":"depth","t":"depth: Int","d":"org.abh80.nf.frames.Frame","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"org.abh80.nf.frames.Frame","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame.html#parent-0","e":false,"i":"","n":"parent","t":"parent: Option[Frame]","d":"org.abh80.nf.frames.Frame","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame.html#pseudoInertial-0","e":false,"i":"","n":"pseudoInertial","t":"pseudoInertial: Boolean","d":"org.abh80.nf.frames.Frame","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame.html#transformProvider-0","e":false,"i":"","n":"transformProvider","t":"transformProvider: ReferenceFrameTransformProvider","d":"org.abh80.nf.frames.Frame","k":"val","x":""},
{"l":"org/abh80/nf/frames/Frame$.html#","e":false,"i":"","n":"Frame","t":"Frame","d":"org.abh80.nf.frames","k":"object","x":""},
{"l":"org/abh80/nf/orbit.html#","e":false,"i":"","n":"org.abh80.nf.orbit","t":"org.abh80.nf.orbit","d":"","k":"package","x":""},
{"l":"org/abh80/nf/orbit/CircularOrbit.html#","e":false,"i":"","n":"CircularOrbit","t":"CircularOrbit","d":"org.abh80.nf.orbit","k":"class","x":""},
{"l":"org/abh80/nf/orbit/KeplerianOrbit.html#","e":false,"i":"","n":"KeplerianOrbit","t":"KeplerianOrbit","d":"org.abh80.nf.orbit","k":"class","x":""},
{"l":"org/abh80/nf/orbit/Orbit.html#","e":false,"i":"","n":"Orbit","t":"Orbit","d":"org.abh80.nf.orbit","k":"trait","x":""},
{"l":"org/abh80/nf/util.html#","e":false,"i":"","n":"org.abh80.nf.util","t":"org.abh80.nf.util","d":"","k":"package","x":""},
{"l":"org/abh80/nf/util/DateUtil$.html#","e":false,"i":"","n":"DateUtil","t":"DateUtil","d":"org.abh80.nf.util","k":"object","x":""},
{"l":"org/abh80/nf/util/DateUtil$.html#DateSeparator-0","e":false,"i":"","n":"DateSeparator","t":"DateSeparator = String","d":"org.abh80.nf.util.DateUtil","k":"type","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ANSI_INCITS_30_1997.html#","e":false,"i":"","n":"ANSI_INCITS_30_1997","t":"ANSI_INCITS_30_1997(dd: Int, mm: Int, yyyy: Int) extends StringDateFormat","d":"org.abh80.nf.util.DateUtil","k":"class","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ANSI_INCITS_30_1997.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.ANSI_INCITS_30_1997","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ANSI_INCITS_30_1997.html#sep-0","e":false,"i":"","n":"sep","t":"sep: DateSeparator","d":"org.abh80.nf.util.DateUtil.ANSI_INCITS_30_1997","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ASIAN.html#","e":false,"i":"","n":"ASIAN","t":"ASIAN(dd: Int, mm: Int, yyyy: Int) extends StringDateFormat","d":"org.abh80.nf.util.DateUtil","k":"class","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ASIAN.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.ASIAN","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ASIAN.html#sep-0","e":false,"i":"","n":"sep","t":"sep: DateSeparator","d":"org.abh80.nf.util.DateUtil.ASIAN","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateName.html#","e":false,"i":"","n":"DateName","t":"DateName","d":"org.abh80.nf.util.DateUtil","k":"trait","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateName.html#toCapitalizedString-0","e":false,"i":"","n":"toCapitalizedString","t":"toCapitalizedString: String","d":"org.abh80.nf.util.DateUtil.DateName","k":"def","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateSeparator$.html#","e":false,"i":"","n":"DateSeparator","t":"DateSeparator","d":"org.abh80.nf.util.DateUtil","k":"object","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateSeparator$.html#dot-0","e":false,"i":"","n":"dot","t":"dot: DateSeparator","d":"org.abh80.nf.util.DateUtil.DateSeparator","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateSeparator$.html#hyphen-0","e":false,"i":"","n":"hyphen","t":"hyphen: DateSeparator","d":"org.abh80.nf.util.DateUtil.DateSeparator","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$DateSeparator$.html#slash-0","e":false,"i":"","n":"slash","t":"slash: DateSeparator","d":"org.abh80.nf.util.DateUtil.DateSeparator","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$EN28601.html#","e":false,"i":"","n":"EN28601","t":"EN28601(dd: Int, mm: Int, yyyy: Int) extends StringDateFormat","d":"org.abh80.nf.util.DateUtil","k":"class","x":""},
{"l":"org/abh80/nf/util/DateUtil$$EN28601.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.EN28601","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$EN28601.html#sep-0","e":false,"i":"","n":"sep","t":"sep: DateSeparator","d":"org.abh80.nf.util.DateUtil.EN28601","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ISO8601.html#","e":false,"i":"","n":"ISO8601","t":"ISO8601(dd: Int, mm: Int, yyyy: Int) extends StringDateFormat","d":"org.abh80.nf.util.DateUtil","k":"class","x":""},
{"l":"org/abh80/nf/util/DateUtil$$ISO8601.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.ISO8601","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#","e":false,"i":"","n":"Month","t":"Month(val asInt: Int) extends DateName","d":"org.abh80.nf.util.DateUtil","k":"enum","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#JANUARY-0","e":false,"i":"","n":"JANUARY","t":"JANUARY extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#FEBRUARY-0","e":false,"i":"","n":"FEBRUARY","t":"FEBRUARY extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#MARCH-0","e":false,"i":"","n":"MARCH","t":"MARCH extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#APRIL-0","e":false,"i":"","n":"APRIL","t":"APRIL extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#MAY-0","e":false,"i":"","n":"MAY","t":"MAY extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#JUNE-0","e":false,"i":"","n":"JUNE","t":"JUNE extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#JULY-0","e":false,"i":"","n":"JULY","t":"JULY extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#AUGUST-0","e":false,"i":"","n":"AUGUST","t":"AUGUST extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#SEPTEMBER-0","e":false,"i":"","n":"SEPTEMBER","t":"SEPTEMBER extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#OCTOBER-0","e":false,"i":"","n":"OCTOBER","t":"OCTOBER extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#NOVEMBER-0","e":false,"i":"","n":"NOVEMBER","t":"NOVEMBER extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month.html#DECEMBER-0","e":false,"i":"","n":"DECEMBER","t":"DECEMBER extends Month","d":"org.abh80.nf.util.DateUtil.Month","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month$.html#","e":false,"i":"","n":"Month","t":"Month","d":"org.abh80.nf.util.DateUtil","k":"object","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Month$.html#getMonth-290","e":false,"i":"","n":"getMonth","t":"getMonth(asInt: Int): Month","d":"org.abh80.nf.util.DateUtil.Month","k":"def","x":""},
{"l":"org/abh80/nf/util/DateUtil$$RFC822.html#","e":false,"i":"","n":"RFC822","t":"RFC822(dd: Int, mm: Int, yyyy: Int, weekDay: Int) extends StringDateFormat","d":"org.abh80.nf.util.DateUtil","k":"class","x":""},
{"l":"org/abh80/nf/util/DateUtil$$RFC822.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.RFC822","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#","e":false,"i":"","n":"StringDateFormat","t":"StringDateFormat(dd: Int, mm: Int, yyyy: Int)","d":"org.abh80.nf.util.DateUtil","k":"trait","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#f_day-0","e":false,"i":"","n":"f_day","t":"f_day: String","d":"org.abh80.nf.util.DateUtil.StringDateFormat","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#f_month-0","e":false,"i":"","n":"f_month","t":"f_month: String","d":"org.abh80.nf.util.DateUtil.StringDateFormat","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#f_year-0","e":false,"i":"","n":"f_year","t":"f_year: String","d":"org.abh80.nf.util.DateUtil.StringDateFormat","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#formatted3partitionTuple-0","e":false,"i":"","n":"formatted3partitionTuple","t":"formatted3partitionTuple: (String, String, String)","d":"org.abh80.nf.util.DateUtil.StringDateFormat","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$StringDateFormat.html#sep-0","e":false,"i":"","n":"sep","t":"sep: DateSeparator","d":"org.abh80.nf.util.DateUtil.StringDateFormat","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$WeekUtil$.html#","e":false,"i":"","n":"WeekUtil","t":"WeekUtil","d":"org.abh80.nf.util.DateUtil","k":"object","x":""},
{"l":"org/abh80/nf/util/DateUtil$$WeekUtil$.html#fromInt-fffffb38","e":false,"i":"","n":"fromInt","t":"fromInt(asInt: Int): Weekday","d":"org.abh80.nf.util.DateUtil.WeekUtil","k":"def","x":""},
{"l":"org/abh80/nf/util/DateUtil$$WeekUtil$.html#isWeekday-201","e":false,"i":"","n":"isWeekday","t":"isWeekday(day: Weekday): Boolean","d":"org.abh80.nf.util.DateUtil.WeekUtil","k":"def","x":""},
{"l":"org/abh80/nf/util/DateUtil$$WeekUtil$.html#isWeekend-201","e":false,"i":"","n":"isWeekend","t":"isWeekend(day: Weekday): Boolean","d":"org.abh80.nf.util.DateUtil.WeekUtil","k":"def","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#","e":false,"i":"","n":"Weekday","t":"Weekday(asInt: Int) extends DateName","d":"org.abh80.nf.util.DateUtil","k":"enum","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#MONDAY-0","e":false,"i":"","n":"MONDAY","t":"MONDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#TUESDAY-0","e":false,"i":"","n":"TUESDAY","t":"TUESDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#WEDNESDAY-0","e":false,"i":"","n":"WEDNESDAY","t":"WEDNESDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#THURSDAY-0","e":false,"i":"","n":"THURSDAY","t":"THURSDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#FRIDAY-0","e":false,"i":"","n":"FRIDAY","t":"FRIDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#SATURDAY-0","e":false,"i":"","n":"SATURDAY","t":"SATURDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/DateUtil$$Weekday.html#SUNDAY-0","e":false,"i":"","n":"SUNDAY","t":"SUNDAY extends Weekday","d":"org.abh80.nf.util.DateUtil.Weekday","k":"val","x":""},
{"l":"org/abh80/nf/util/TimeShiftable.html#","e":false,"i":"","n":"TimeShiftable","t":"TimeShiftable[T]","d":"org.abh80.nf.util","k":"trait","x":""},
{"l":"org/abh80/nf/util/TimeShiftable.html#++-12c","e":false,"i":"","n":"++","t":"++(dt: Double): T","d":"org.abh80.nf.util.TimeShiftable","k":"def","x":""},
{"l":"org/abh80/nf/util/TimeShiftable.html#++-fffff3e6","e":false,"i":"","n":"++","t":"++(timeFormat: TimeFormat): T","d":"org.abh80.nf.util.TimeShiftable","k":"def","x":""},
{"l":"org/abh80/nf/util/TimeShiftable.html#shiftBy-12c","e":false,"i":"","n":"shiftBy","t":"shiftBy(dt: Double): T","d":"org.abh80.nf.util.TimeShiftable","k":"def","x":""},
{"l":"org/abh80/nf/util/TimeShiftable.html#shiftBy-fffff3e6","e":false,"i":"","n":"shiftBy","t":"shiftBy(timeFormat: TimeFormat): T","d":"org.abh80.nf.util.TimeShiftable","k":"def","x":""}];